export interface CryptoData {
  id: string;
  name: string;
  value: string;
  color: string;
}

// Define colors from the design
const colors = {
  green: "#089950",
  darkGreen: "#056636",
  mediumGreen: "#42bd7f",
  lightGreen: "#42bd7f",
  gray: "#b8b8b8",
  red: "#f23645",
  lightRed: "#f77c80",
  lightPink: "#ffb2b9",
};

// Generate sample data for the top 100+ cryptocurrencies
export function generateCryptoData(): CryptoData[] {
  return [
    { id: "btc", name: "Bitcoin", value: "$850.24 B", color: colors.green },
    { id: "eth", name: "Ethereum", value: "$400.12 B", color: colors.darkGreen },
    { id: "bnb", name: "BNB", value: "$70.89 B", color: colors.mediumGreen },
    { id: "sol", name: "Solana", value: "$55.21 B", color: colors.darkGreen },
    { id: "xrp", name: "XRP", value: "$35.56 B", color: colors.mediumGreen },
    { id: "ada", name: "Cardano", value: "$30.42 B", color: colors.mediumGreen },
    { id: "doge", name: "Dogecoin", value: "$22.78 B", color: colors.darkGreen },
    { id: "ton", name: "Toncoin", value: "$18.24 B", color: colors.lightRed },
    { id: "dot", name: "Polkadot", value: "$16.93 B", color: colors.darkGreen },
    { id: "matic", name: "Polygon", value: "$14.87 B", color: colors.lightGreen },
    { id: "ltc", name: "Litecoin", value: "$12.78 B", color: colors.darkGreen },
    { id: "shib", name: "Shiba Inu", value: "$11.62 B", color: colors.darkGreen },
    { id: "avax", name: "Avalanche", value: "$10.54 B", color: colors.lightRed },
    { id: "uni", name: "Uniswap", value: "$9.38 B", color: colors.mediumGreen },
    { id: "link", name: "Chainlink", value: "$8.96 B", color: colors.darkGreen },
    { id: "xlm", name: "Stellar", value: "$7.25 B", color: colors.gray },
    { id: "bch", name: "Bitcoin Cash", value: "$6.98 B", color: colors.mediumGreen },
    { id: "near", name: "Near Protocol", value: "$6.45 B", color: colors.lightRed },
    { id: "ape", name: "ApeCoin", value: "$5.87 B", color: colors.lightPink },
    { id: "fil", name: "Filecoin", value: "$5.23 B", color: colors.red },
    { id: "algo", name: "Algorand", value: "$4.85 B", color: colors.darkGreen },
    { id: "qnt", name: "Quant", value: "$4.62 B", color: colors.mediumGreen },
    { id: "ftm", name: "Fantom", value: "$4.21 B", color: colors.lightGreen },
    { id: "icp", name: "Internet Computer", value: "$3.98 B", color: colors.darkGreen },
    { id: "hbar", name: "Hedera", value: "$3.78 B", color: colors.lightRed },
    { id: "egld", name: "MultiversX", value: "$3.42 B", color: colors.mediumGreen },
    { id: "mana", name: "Decentraland", value: "$3.21 B", color: colors.lightPink },
    { id: "sand", name: "The Sandbox", value: "$3.07 B", color: colors.red },
    { id: "theta", name: "Theta Network", value: "$2.94 B", color: colors.darkGreen },
    { id: "axs", name: "Axie Infinity", value: "$2.83 B", color: colors.lightGreen },
    { id: "flow", name: "Flow", value: "$2.69 B", color: colors.mediumGreen },
    { id: "hnt", name: "Helium", value: "$2.53 B", color: colors.darkGreen },
    { id: "rose", name: "Oasis Network", value: "$2.42 B", color: colors.lightRed },
    { id: "rune", name: "THORChain", value: "$2.31 B", color: colors.green },
    { id: "zil", name: "Zilliqa", value: "$2.14 B", color: colors.mediumGreen },
    { id: "dash", name: "Dash", value: "$2.05 B", color: colors.darkGreen },
    { id: "neo", name: "NEO", value: "$1.92 B", color: colors.red },
    { id: "gala", name: "Gala", value: "$1.84 B", color: colors.lightPink },
    { id: "enj", name: "Enjin Coin", value: "$1.72 B", color: colors.gray },
    { id: "bat", name: "Basic Attention Token", value: "$1.65 B", color: colors.mediumGreen },
    { id: "one", name: "Harmony", value: "$1.58 B", color: colors.darkGreen },
    { id: "lrc", name: "Loopring", value: "$1.42 B", color: colors.red },
    { id: "cvx", name: "Convex Finance", value: "$1.38 B", color: colors.lightRed },
    { id: "comp", name: "Compound", value: "$1.29 B", color: colors.green },
    { id: "aave", name: "Aave", value: "$1.24 B", color: colors.darkGreen },
    { id: "ftt", name: "FTX Token", value: "$1.18 B", color: colors.mediumGreen },
    { id: "chz", name: "Chiliz", value: "$1.11 B", color: colors.lightGreen },
    { id: "waves", name: "Waves", value: "$1.03 B", color: colors.lightPink },
    { id: "kava", name: "Kava", value: "$0.98 B", color: colors.darkGreen },
    { id: "zec", name: "Zcash", value: "$0.92 B", color: colors.mediumGreen },
    { id: "stx", name: "Stacks", value: "$0.87 B", color: colors.lightRed },
    { id: "crv", name: "Curve DAO Token", value: "$0.82 B", color: colors.green },
    { id: "snx", name: "Synthetix", value: "$0.78 B", color: colors.darkGreen },
    { id: "uma", name: "UMA", value: "$0.74 B", color: colors.mediumGreen },
    { id: "yfi", name: "Yearn.finance", value: "$0.69 B", color: colors.lightGreen },
    { id: "ren", name: "Ren", value: "$0.65 B", color: colors.red },
    { id: "rsr", name: "Reserve Rights", value: "$0.61 B", color: colors.lightPink },
    { id: "ogn", name: "Origin Protocol", value: "$0.57 B", color: colors.gray },
    { id: "celo", name: "Celo", value: "$0.53 B", color: colors.darkGreen },
    { id: "skl", name: "SKALE Network", value: "$0.49 B", color: colors.mediumGreen },
    { id: "ankr", name: "Ankr", value: "$0.45 B", color: colors.lightRed },
    { id: "oxt", name: "Orchid", value: "$0.41 B", color: colors.green },
    { id: "nkn", name: "NKN", value: "$0.38 B", color: colors.darkGreen },
    { id: "dydx", name: "dYdX", value: "$0.35 B", color: colors.mediumGreen },
    { id: "api3", name: "API3", value: "$0.29 B", color: colors.red },
    { id: "rad", name: "Radicle", value: "$0.26 B", color: colors.lightPink },
    { id: "mir", name: "Mirror Protocol", value: "$0.23 B", color: colors.gray },
    { id: "tribe", name: "Tribe", value: "$0.20 B", color: colors.darkGreen },
    { id: "alcx", name: "Alchemix", value: "$0.18 B", color: colors.mediumGreen },
    { id: "badger", name: "Badger DAO", value: "$0.15 B", color: colors.lightRed },
    { id: "fxs", name: "Frax Share", value: "$0.12 B", color: colors.green },
    { id: "grt", name: "The Graph", value: "$0.10 B", color: colors.darkGreen },
    { id: "keep", name: "Keep Network", value: "$0.06 B", color: colors.lightGreen },
    { id: "nu", name: "NuCypher", value: "$0.04 B", color: colors.red },
    { id: "mkr", name: "Maker", value: "$0.02 B", color: colors.lightPink },
    // Additional cryptocurrencies
    { id: "iotx", name: "IoTeX", value: "$0.50 B", color: colors.mediumGreen },
    { id: "ont", name: "Ontology", value: "$0.48 B", color: colors.darkGreen },
    { id: "sc", name: "Siacoin", value: "$0.46 B", color: colors.lightRed },
    { id: "hbar", name: "Hedera", value: "$0.44 B", color: colors.green },
    { id: "rvn", name: "Ravencoin", value: "$0.42 B", color: colors.mediumGreen },
    { id: "ar", name: "Arweave", value: "$0.40 B", color: colors.lightPink },
    { id: "zen", name: "Horizen", value: "$0.38 B", color: colors.red },
    { id: "srm", name: "Serum", value: "$0.36 B", color: colors.darkGreen },
    { id: "luna", name: "Terra", value: "$0.34 B", color: colors.mediumGreen },
    { id: "uma", name: "UMA", value: "$0.32 B", color: colors.lightGreen },
    { id: "bal", name: "Balancer", value: "$0.30 B", color: colors.gray },
    { id: "rlc", name: "iExec RLC", value: "$0.28 B", color: colors.lightRed },
    { id: "uma", name: "UMA", value: "$0.26 B", color: colors.green },
    { id: "uma", name: "UMA", value: "$0.24 B", color: colors.darkGreen },
    { id: "uma", name: "UMA", value: "$0.22 B", color: colors.mediumGreen },
    { id: "uma", name: "UMA", value: "$0.20 B", color: colors.lightPink },
    { id: "uma", name: "UMA", value: "$0.18 B", color: colors.red },
    { id: "uma", name: "UMA", value: "$0.16 B", color: colors.gray },
    { id: "uma", name: "UMA", value: "$0.14 B", color: colors.darkGreen },
    { id: "uma", name: "UMA", value: "$0.12 B", color: colors.mediumGreen },
    { id: "uma", name: "UMA", value: "$0.10 B", color: colors.lightGreen },
  ];
}